image_size: [96, 96]
context_type: temporal
normalize: true
clip_model: ViT-B/32

datasets:
  sample:
    data_folder: <dataset_name>
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1 # how many goals are sampled per observation
    waypoint_spacing: 1 # moveing distance between waypoints in one meters
    metric_waypoint_spacing: 1.0 # frame number between waypoints in one meters
    modality_id: 7

# modality flags (pose/image/language) are derived automatically from modality_id
# 0: satellite only
# 1: pose and satellite
# 2: satellite and image
# 3: all
# 4: pose only
# 5: pose and image
# 6: image only
# 7: language only
# 8: language and pose
