#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional

import torch

from .toponav import TopomapGenerator


def main(args: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("dataset_path", help="Dataset directory generated by create_data.py")
    parser.add_argument(
        "--output-dir",
        default="deployment/config/topomap",
        help="Directory where topomap.yaml and images/ are written",
    )
    parser.add_argument(
        "--weights",
        default="deployment/weights/placenet.pt",
        help="PlaceNet TorchScript weight path",
    )
    parser.add_argument("--saved-step", type=int, default=10, help="Use every Nth dataset image as a node")
    parser.add_argument("--crop-size", type=int, default=288, help="Center crop size before resizing to 85x85")
    parsed = parser.parse_args(args)

    repo_root = Path(__file__).resolve().parents[2]
    dataset_path = Path(parsed.dataset_path).expanduser()
    output_dir = Path(parsed.output_dir).expanduser()
    weights_path = Path(parsed.weights).expanduser()

    if not dataset_path.is_absolute():
        dataset_path = repo_root / dataset_path
    if not output_dir.is_absolute():
        output_dir = repo_root / output_dir
    if not weights_path.is_absolute():
        weights_path = repo_root / weights_path

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    generator = TopomapGenerator(
        dataset_path=dataset_path,
        output_dir=output_dir,
        weight_path=weights_path,
        device=device,
        saved_step=parsed.saved_step,
        crop_size=parsed.crop_size,
    )
    topomap_path = generator.generate()
    print(f"Topomap saved: {topomap_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
